### ISSUE TITLE
Enable crypt support

### ISSUE THREAD

**Issue by kyak** [allanmcrae/toolchain#1]
So here it goes. Users start nagging about your toolchain and asking for features :)

Allan, can you please enable crypt support? You have currently disabled it explicitly:

https://github.com/allanmcrae/toolchain/blob/5c2bb5710e1bafad4d92e7e46bed09bf0cda872e/glibc/PKGBUILD#L58

There are programs that link to `libcrypt.so.1` (used to be) provided by `glibc` and won't work with `libcrypt.so.2` as provided by `core/libxcrypt`.

**Comment by allanmcrae** [comment]
Fedora also removes this library from F28 (released May 2018) - it is time other software caught up.

**Comment by kyak** [comment]
If anybody needs legacy `libcrypto.so.1`, you can use https://aur.archlinux.org/packages/libxcrypt-compat/
