### ISSUE TITLE
Dropping languages

### ISSUE THREAD

**Issue by FFY00** [allanmcrae/toolchain#2]
> No support for Ada, D or ObjC
>
> No-one really needs those languages anyway.

Hum... I did maintain GDC (the GCC D compiler) before it was merged into GCC, so  I'd say there is a need for it. Similarly, Ada, even though it is more of a niche, it does find some use in key tools related to hardware design, namely [GHDL](https://github.com/ghdl/ghdl).

I don't think these languages need to live in the same PKGBUILD as the main GCC compiler, but suggesting simply dropping them is misguided.

**Comment by allanmcrae** [comment]
Don't use these packages then.
